//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFTWallet.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFTWallet.Resources.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Place Bid.
        /// </summary>
        internal static string DetailButtonBid {
            get {
                return ResourceManager.GetString("DetailButtonBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Latest bids.
        /// </summary>
        internal static string DetailLabelLatestBids {
            get {
                return ResourceManager.GetString("DetailLabelLatestBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detail.
        /// </summary>
        internal static string DetailLabelTitle {
            get {
                return ResourceManager.GetString("DetailLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Let&apos;s Start.
        /// </summary>
        internal static string GetStartedButton {
            get {
                return ResourceManager.GetString("GetStartedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Discover the Most Premium, Unique and Exclusive NFT Collections.
        /// </summary>
        internal static string GetStartedLabelSubtitle {
            get {
                return ResourceManager.GetString("GetStartedLabelSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SUCURI NFT.
        /// </summary>
        internal static string GetStartedLabelTitle {
            get {
                return ResourceManager.GetString("GetStartedLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Owned by.
        /// </summary>
        internal static string HomeLabelOwnedBy {
            get {
                return ResourceManager.GetString("HomeLabelOwnedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        internal static string HomePlaceholderSearch {
            get {
                return ResourceManager.GetString("HomePlaceholderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login with Metamesk.
        /// </summary>
        internal static string LoginButtonMetamesk {
            get {
                return ResourceManager.GetString("LoginButtonMetamesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forgot password?.
        /// </summary>
        internal static string LoginLabelForgotPassword {
            get {
                return ResourceManager.GetString("LoginLabelForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not registered yet?.
        /// </summary>
        internal static string LoginLabelNotResgistered {
            get {
                return ResourceManager.GetString("LoginLabelNotResgistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a or.
        /// </summary>
        internal static string LoginLabelOr {
            get {
                return ResourceManager.GetString("LoginLabelOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register.
        /// </summary>
        internal static string LoginLabelRegister {
            get {
                return ResourceManager.GetString("LoginLabelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Discover the Most Premium, Unique and Exclusive NFT Collections.
        /// </summary>
        internal static string LoginLabelSubtitle {
            get {
                return ResourceManager.GetString("LoginLabelSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string LoginLabelTitle {
            get {
                return ResourceManager.GetString("LoginLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        internal static string LoginPlaceholderEmail {
            get {
                return ResourceManager.GetString("LoginPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password.
        /// </summary>
        internal static string LoginPlaceholderPassword {
            get {
                return ResourceManager.GetString("LoginPlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Followers.
        /// </summary>
        internal static string ProfileLabelFollowers {
            get {
                return ResourceManager.GetString("ProfileLabelFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Following.
        /// </summary>
        internal static string ProfileLabelFollowing {
            get {
                return ResourceManager.GetString("ProfileLabelFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Likes.
        /// </summary>
        internal static string ProfileLabelLikes {
            get {
                return ResourceManager.GetString("ProfileLabelLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dark Theme.
        /// </summary>
        internal static string SettingsLabelDark {
            get {
                return ResourceManager.GetString("SettingsLabelDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Favorites.
        /// </summary>
        internal static string SettingsLabelFavorites {
            get {
                return ResourceManager.GetString("SettingsLabelFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Help &amp; Support.
        /// </summary>
        internal static string SettingsLabelHelp {
            get {
                return ResourceManager.GetString("SettingsLabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string SettingsLabelLanguage {
            get {
                return ResourceManager.GetString("SettingsLabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logout.
        /// </summary>
        internal static string SettingsLabelLogout {
            get {
                return ResourceManager.GetString("SettingsLabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notification.
        /// </summary>
        internal static string SettingsLabelNotification {
            get {
                return ResourceManager.GetString("SettingsLabelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password.
        /// </summary>
        internal static string SettingsLabelPassword {
            get {
                return ResourceManager.GetString("SettingsLabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Privacy Policy.
        /// </summary>
        internal static string SettingsLabelPrivacy {
            get {
                return ResourceManager.GetString("SettingsLabelPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Settings.
        /// </summary>
        internal static string SettingsLabelTitle {
            get {
                return ResourceManager.GetString("SettingsLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transfer NFT.
        /// </summary>
        internal static string SettingsLabelTransfer {
            get {
                return ResourceManager.GetString("SettingsLabelTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wallet.
        /// </summary>
        internal static string SettingsLabelWallet {
            get {
                return ResourceManager.GetString("SettingsLabelWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Most recent.
        /// </summary>
        internal static string TrendsLabelOrder {
            get {
                return ResourceManager.GetString("TrendsLabelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The top NFT&apos;s ranked by sales volume and values.
        /// </summary>
        internal static string TrendsLabelSubtitle {
            get {
                return ResourceManager.GetString("TrendsLabelSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Trends.
        /// </summary>
        internal static string TrendsLabelTitle {
            get {
                return ResourceManager.GetString("TrendsLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deposit.
        /// </summary>
        internal static string WalletLabelDeposit {
            get {
                return ResourceManager.GetString("WalletLabelDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send.
        /// </summary>
        internal static string WalletLabelSend {
            get {
                return ResourceManager.GetString("WalletLabelSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wallet.
        /// </summary>
        internal static string WalletLabelTitle {
            get {
                return ResourceManager.GetString("WalletLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transactions.
        /// </summary>
        internal static string WalletLabelTransactions {
            get {
                return ResourceManager.GetString("WalletLabelTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Withdrawal.
        /// </summary>
        internal static string WalletLabelWithdrawal {
            get {
                return ResourceManager.GetString("WalletLabelWithdrawal", resourceCulture);
            }
        }
    }
}
